### ISSUE TITLE
wmts-v_1_0 - 2.6.1 - TileMatrix.getTopLeftCorner List<Double> contains String values

### ISSUE THREAD

**Issue by shruda** [highsource/ogc-schemas#173] opened 2016-04-29 11:25 UTC
Hi,
if I try to get a double value from the TileMatrix's TopLeftCorner list, than I'll get a ClassCastException:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double

    double value = tileMatrix.getTopLeftCorner().get(0);

Best Regards,
Steve

**Comment by highsource** [comment] 2016-05-09 18:54
Reproduced. This is due to:

https://java.net/jira/browse/JAXB-986

**Comment by highsource** [comment] 2016-05-09 19:21
Should be fixed now. Please build `wmts-v_1_0` in the current snapshot and try again.

**Closed** 2016-05-09 19:20 UTC
Labels: bug
